package ui;

import javax.swing.border.*;
import javax.swing.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.Dialog.*;
import java.sql.*;
import java.util.GregorianCalendar;;


import domain.Member;
import control.CustomerControl;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jonas
 */
public class MemberFrame extends javax.swing.JFrame {
    private CustomerControl customerControl;
    ArrayList<Member> member;
    private JPanel tableLayout = new JPanel();
    private String memberID;
    Object[] columnName = {"Member ID", "Register Date", "Point", "First Name", "Last Name", "Address", "IC", "Date of Birth", "Email", "Phone No."};
    private JTable memberTable;
    
    /**
     * Creates new form Member
     */
    public MemberFrame() {
        initComponents();
        customerControl=new CustomerControl();
        setDataToTable();
        //pack();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Member List");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"B001", null,  new Integer(1000), "Ong Shun Min", null, "Tamn Anne", "17-05-13", null, "Male", "014 8372957"},
                {"B002", null,  new Integer(300), "Fendy", null, "Sri Pelangi Coned", "13-04-15", null, "Female", "016 3672839"},
                {"B003", null,  new Integer(700), "Joey", null, "Gobakik", "02-12-16", null, "Female", "017 37463823"},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Register Date", "Loyalty Point", "First Name", "Last Name", "Address", "IC", "Date of Birth", "Email", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Redeem");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        this.dispose();    
        new AddMember();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            int choice = JOptionPane.showConfirmDialog(null, "Do you confirm?", "Remove Member", JOptionPane.YES_NO_OPTION);
            Member mem = new Member();
            mem.setMemberID((String)jTable1.getValueAt(selectedRow, 0));
            if(choice == JOptionPane.YES_OPTION){
                customerControl.deleteItem(mem);
                
            }
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Select a row !!");
        }    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRowIndex = jTable1.getSelectedRow();
        int point = (int) (jTable1.getValueAt(selectedRowIndex, 2));
        String memberID = (String) (jTable1.getValueAt(selectedRowIndex, 0));
        String firstName = (String) (jTable1.getValueAt(selectedRowIndex, 3));
        String lastName  = (String) (jTable1.getValueAt(selectedRowIndex, 4));
        String address = (String) (jTable1.getValueAt(selectedRowIndex, 5));
        String IC = (String) (jTable1.getValueAt(selectedRowIndex, 6));
        String email = (String) (jTable1.getValueAt(selectedRowIndex, 8));
        String phoneNo = (String) (jTable1.getValueAt(selectedRowIndex, 9));
        
        if (selectedRowIndex >= 0) {
            String date = (String) jTable1.getValueAt(selectedRowIndex, 1);
            GregorianCalendar registerdate = new GregorianCalendar(Integer.parseInt(date.substring(0,4)),Integer.parseInt(date.substring(5,7)),Integer.parseInt(date.substring(8)));

            date = (String) jTable1.getValueAt(selectedRowIndex, 7);
            GregorianCalendar DOB = new GregorianCalendar(Integer.parseInt(date.substring(0,4)),Integer.parseInt(date.substring(5,7)),Integer.parseInt(date.substring(8)));
            
//            System.out.println(jTable1.getValueAt(selectedRowIndex, 0) + " " + jTable1.getValueAt(selectedRowIndex, 1) + " " + jTable1.getValueAt(selectedRowIndex, 2)
//                + " " + jTable1.getValueAt(selectedRowIndex, 7) + " " + jTable1.getValueAt(selectedRowIndex, 9) + " " + date);
            
//            if(firstName instanceof Object){
//                System.out.println("Yes. FirstName is Object.");
//            }
            
            Member mem = new Member(memberID, registerdate, point, firstName, lastName, address, IC, DOB, email, phoneNo);
            
            this.setVisible(false);
            this.dispose();
            new UpdateMember(mem);
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a row !!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberFrame().setVisible(true);
            }
        });
    }
    
    private void setDataToTable() {
        ArrayList<Member> member = customerControl.getRecord();
        String BODate;
        String registerDate;
        for(int i=0;i<member.size();i++){
                    registerDate = String.format("%04d-%02d-%02d",member.get(i).getRegisterDate().get(Calendar.YEAR),member.get(i).getRegisterDate().get(Calendar.MONTH),member.get(i).getRegisterDate().get(Calendar.DATE) ) ;
                    BODate = String.format("%04d-%02d-%02d",member.get(i).getDOB().get(Calendar.YEAR),member.get(i).getDOB().get(Calendar.MONTH),member.get(i).getDOB().get(Calendar.DATE) ) ;
                    jTable1.setValueAt(member.get(i).getMemberID(), i, 0);
                    jTable1.setValueAt(registerDate, i, 1);
                    jTable1.setValueAt(member.get(i).getPoint(), i, 2);
                    jTable1.setValueAt(member.get(i).getFirstName(), i, 3);
                    jTable1.setValueAt(member.get(i).getLastName(), i, 4);
                    jTable1.setValueAt(member.get(i).getAddress(), i, 5);
                    jTable1.setValueAt(member.get(i).getIC(), i, 6);
                    jTable1.setValueAt(BODate, i, 7);
                    jTable1.setValueAt(member.get(i).getEmail(), i, 8);
                    jTable1.setValueAt(member.get(i).getPhoneNo(), i, 9);
        }
        
        
        
        
        
//        tableLayout.removeAll();
//        tableLayout.updateUI();
//        tableLayout.repaint();
//        
//        Object [][] tableElements = new Object[member.size()][columnName.length];
//        
//        
//        for(int i=0; i<member.size(); i++) {
//            for(int j=0; j<columnName.length; j++) {
//                switch(j){
//                    case 0:
//                        tableElements[i][j] = member.get(i).getMemberID();
//                        break;
//                    case 1:
//                        tableElements[i][j] = member.get(i).getRegisterDate();
//                        break;
//                    case 2:
//                        tableElements[i][j] = member.get(i).getPoint();
//                        break;
//                    case 3:
//                        tableElements[i][j] = member.get(i).getFirstName();
//                        break;
//                    case 4:
//                        tableElements[i][j] = member.get(i).getLastName();
//                        break;
//                    case 5:
//                        tableElements[i][j] = member.get(i).getAddress();
//                        break;
//                    case 6:
//                        tableElements[i][j] = member.get(i).getIC();
//                        break;
//                    case 7:
//                        tableElements[i][j] = member.get(i).getDOB();
//                        break;
//                    case 8:
//                        tableElements[i][j] = member.get(i).getEmail();
//                        break;
//                    case 9:
//                        tableElements[i][j] = member.get(i).getPhoneNo();
//                }
//            }
//        }
//        
//        memberTable = new JTable(tableElements, columnName) {
//            //use to make cell uneditable but selectable for user
//            private static final long serialVersionUID = 1L;
//           
//            public boolean isCellEditable(int row, int column) {
//                return false;
//            }
//        };
//                
//        memberTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        memberTable.getTableHeader().setReorderingAllowed(false);
//        
//        JScrollPane tableOrder = new JScrollPane(memberTable);
//        tableOrder.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//        tableOrder.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
//        
//        tableLayout.add(tableOrder);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
